## Slicing

In [1]:
import numpy as np

In [2]:
array2 = np.array([2,3,4,5,6,7,9])
print(array2)

[2 3 4 5 6 7 9]


In [3]:
%%debug
arr = array2[4:6].copy()
print(arr)

NOTE: Enter 'c' at the ipdb>  prompt to continue execution.
> <string>(2)<module>()

ipdb> c
[6 7]


In [4]:
arr[0]=11

In [5]:
array2

array([2, 3, 4, 5, 6, 7, 9])

In [6]:
ar1 = np.array([[1,2,3],[4,6,7]])
print(ar1)

[[1 2 3]
 [4 6 7]]


In [7]:
ar1.sum(axis = 1)

array([ 6, 17])

In [8]:
b = np.array([[2,3,4],[3,5,6]])

In [9]:
ar1.dot(b.transpose())

array([[20, 31],
       [54, 84]])

In [10]:
np.cross(ar1,b)

array([[-1,  2, -1],
       [ 1, -3,  2]])

## Sorting

In [11]:
%%time
np.sort(ar1,axis = 0,kind = "quicksort")

Wall time: 0 ns


array([[1, 2, 3],
       [4, 6, 7]])

In [12]:
a = np.arange(2,20)
a.shape
a.reshape(6,3)

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [13]:
np.argsort(a)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17], dtype=int64)

In [14]:
np.argmax(a)

17

In [15]:
np.argmin(a)

0

In [16]:
import pandas as pd
import numpy as np