<h1 style="color:green" align='center'>Numpy tutorial: iterate numpy array using nditer</h1>

In [1]:
# less memory,fast,convinient
# # Numpy is a general-purpose array-processing package

In [2]:
import numpy as np
import time
import sys

In [3]:
# numpy is faster and take less memory than list

ran = 10000000
lis1 = range(ran)
lis2 = range(ran)
a1 = np.arange(ran)
a2 = np.arange(ran)

print(sys.getsizeof(lis1))

print(a1.size)

print(a1.itemsize)

print(sys.getsizeof(lis1)*len(lis1))

print(a1.size*a1.itemsize)

start = time.time()
result = a1 + a2
print("time require for array in sec",(time.time()-start))

start = time.time()
result = [(x+y) for x,y in zip(lis1,lis2)]
print("time require for list in sec",(time.time()-start))

48
10000000
4
480000000
40000000
time require for array in sec 0.02399444580078125
time require for list in sec 1.9589667320251465


<h2 style = "color:green">Another method to find run time</h2>

In [4]:
%%time
result = [(x+y) for x,y in zip(lis1,lis2)]

Wall time: 2.64 s


In [5]:
%%time
result = a1 + a2

Wall time: 254 ms


In [6]:
# 1D Array 
a = np.array([10,20,30,40, 50])
print(a, type(a))
print(a.dtype)
print(a.size)
print(a.itemsize)
print(a.shape)
#print(dir(a))

[10 20 30 40 50] <class 'numpy.ndarray'>
int32
5
4
(5,)


In [7]:
# 2D Array
mat = np.array( [[1,2,3,4,5,6], [5,7,6,4,55,6]] )
print(mat)
print(mat.shape)
print(mat.dtype)
print(mat.size)
print(mat.itemsize)
mat[0:2]
print(mat[0,2])

[[ 1  2  3  4  5  6]
 [ 5  7  6  4 55  6]]
(2, 6)
int32
12
4
3


In [8]:
a = np.array([10.0,20,30,40, 50])
print(a, type(a))
print(a.dtype)
print(a.itemsize)

[10. 20. 30. 40. 50.] <class 'numpy.ndarray'>
float64
8


In [9]:
mat = np.array([ [1,2,3,4], [3,4,5,6], [1,2,3,4]])
print(mat.shape)
print(mat)

(3, 4)
[[1 2 3 4]
 [3 4 5 6]
 [1 2 3 4]]


In [10]:
a = np.array([10.0,20,30,40, 50], dtype = 'float32')
print(a, type(a))
print(a.dtype)
print(a.itemsize)

[10. 20. 30. 40. 50.] <class 'numpy.ndarray'>
float32
4


In [11]:
a = np.array([100000000000,20,30,40, 50], )
print(a, type(a))
print(a.dtype)
print(a.itemsize)

[100000000000           20           30           40           50] <class 'numpy.ndarray'>
int64
8


In [12]:
a = np.array([10,20,30,128, 50], dtype = 'int8') # -128 - +127
print(a, type(a))
print(a.dtype)
print(a.itemsize)
print(a)

[  10   20   30 -128   50] <class 'numpy.ndarray'>
int8
1
[  10   20   30 -128   50]


In [13]:
a = np.array([10,20,30,256, 50], dtype = 'uint8')
print(a, type(a))
print(a.dtype)
print(a.itemsize)
print(a)

[10 20 30  0 50] <class 'numpy.ndarray'>
uint8
1
[10 20 30  0 50]


In [14]:
a = np.array([10,29], dtype = np.int16)
print(a, a.dtype)
s = a.astype(dtype = 'str')
print(s)
print(s.itemsize)

[10 29] int16
['10' '29']
24


In [15]:
a = np.array([10,29], dtype = 'i8')
print(a, a.dtype)
s = a.astype(dtype = 'str')
print(s)
print(s.itemsize)
print(s.dtype)

[10 29] int64
['10' '29']
84
<U21


In [16]:
a = np.array( [ 1,2,3, 'a', [1,2]] )
print(a)
print(a.dtype)

[1 2 3 'a' list([1, 2])]
object


In [17]:
a = np.arange(1,10)
print(a)
print(a.dtype)
print(type(a))
print(np.arange(10))
print(np.arange(10,20,2))
print(np.arange(10,20,2, dtype = 'f4'))

[1 2 3 4 5 6 7 8 9]
int32
<class 'numpy.ndarray'>
[0 1 2 3 4 5 6 7 8 9]
[10 12 14 16 18]
[10. 12. 14. 16. 18.]


In [18]:
z = np.ones(5, dtype = np.int8)
print(z)
z = np.zeros((5,2), dtype = np.int8)
print(z)

[1 1 1 1 1]
[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]


In [19]:
l = np.arange(1,90,20)
print(l)
l = np.linspace(1,80,40)
print(l)
l = np.linspace(1,10,10)
print(l)
l = np.linspace(1,80,40, dtype = 'int8')
print(l)

l = np.linspace(10,20,10)
print(l)
#(20-10)/(10-1) # AP

[ 1 21 41 61 81]
[ 1.          3.02564103  5.05128205  7.07692308  9.1025641  11.12820513
 13.15384615 15.17948718 17.20512821 19.23076923 21.25641026 23.28205128
 25.30769231 27.33333333 29.35897436 31.38461538 33.41025641 35.43589744
 37.46153846 39.48717949 41.51282051 43.53846154 45.56410256 47.58974359
 49.61538462 51.64102564 53.66666667 55.69230769 57.71794872 59.74358974
 61.76923077 63.79487179 65.82051282 67.84615385 69.87179487 71.8974359
 73.92307692 75.94871795 77.97435897 80.        ]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 80]
[10.         11.11111111 12.22222222 13.33333333 14.44444444 15.55555556
 16.66666667 17.77777778 18.88888889 20.        ]


In [20]:
print((2.0 - 1.0) == (3.0 - 2.0))

f = np.int64(10)/ np.int64(3)
print(f)

True
3.3333333333333335


In [51]:
# print(dir(np.random))
n = np.random.randint(10)
print(n)
n = np.random.randint(10,20)
print(n)
n = np.random.randint(10,20,40)
print(n)
n = np.random.randn(40)
print(n)

6
16
[14 12 13 17 12 15 14 10 16 10 18 14 12 17 18 14 12 14 10 15 16 14 19 17
 14 12 16 11 15 12 13 14 15 14 18 19 17 16 16 12]
[-1.14155743  1.63458279 -0.52879464 -0.17926062 -0.62376709 -0.06972553
  1.33041037 -0.53631349 -0.82488893 -0.66887449 -0.76802942  0.53967701
 -0.62917144 -0.01751139 -0.97846058  0.29544246  1.72695969 -1.56127144
 -0.33932463  0.7658582  -0.47372061  0.44670368 -0.01146946 -1.50312093
  0.38891496 -0.5506709   1.31564921  0.79123047 -0.60564484  0.59735232
 -1.46652859 -0.22636231  0.74211834 -0.74356371  0.13597042  0.64453576
 -0.13515141 -0.9196012   0.04634427  1.52885759]


In [22]:
mat1 = np.arange(1,17).reshape(4,4)
print(mat1)
mat2 = np.arange(1,17).reshape(2,8)
print(mat2)
print(mat1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [23]:
mat1 = np.arange(1,25).reshape(3,2,4)
print(mat1)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]]


In [24]:
mat = np.arange(1,17)
mat.resize(2,20)
print(mat)

mat = np.arange(1,17)
mat.resize(2,5)
print(mat)

[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [25]:
mat1 = np.arange(1,21).reshape(4,5)
print(mat1)

print()
print(mat1[1])
print()
print(mat1[1,1])
print()
print(mat1[1,2])

print()
print(mat1[1:])
print()
print(mat1[1:3, 3])
print()
print(mat1[1:3, :2])
print(mat1[1:3, [1,3]])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

[ 6  7  8  9 10]

7

8

[[ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

[ 9 14]

[[ 6  7]
 [11 12]]
[[ 7  9]
 [12 14]]


In [26]:
mat1 = np.arange(1,21).reshape(4,5)
print(mat1)

print(mat1[3:1:-1, [1,3]]) # [d0, d1,...]
print(mat1[:,4])           #[s0:e0:step0   ,s1:e1:step1....    ]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[17 19]
 [12 14]]
[ 5 10 15 20]


In [27]:
mat1 = np.arange(1,21).reshape(4,5)
print(mat1)
print( mat1 + 20 )

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]]


In [28]:
mat1 = np.arange(1,21).reshape(4,5)
print(mat1)
mat2 = np.arange(100,120).reshape(4,5)
print(mat2)

mat3 = mat1 + mat2
print(mat3)
mat3 = mat1 * mat2
print(mat3)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[100 101 102 103 104]
 [105 106 107 108 109]
 [110 111 112 113 114]
 [115 116 117 118 119]]
[[101 103 105 107 109]
 [111 113 115 117 119]
 [121 123 125 127 129]
 [131 133 135 137 139]]
[[ 100  202  306  412  520]
 [ 630  742  856  972 1090]
 [1210 1332 1456 1582 1710]
 [1840 1972 2106 2242 2380]]


In [29]:
mat1 = np.arange(1,21).reshape(4,5)
print(mat1)
print(mat1.min())
print(mat1.max())
print(mat1.min(axis = 1))
print(mat1.max(axis = 1))
print(mat1.min(axis = 0))
print(mat1.max(axis = 0))
print()
print(mat1.sum(axis = 1))
print(mat1.sum(axis = 1))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
1
20
[ 1  6 11 16]
[ 5 10 15 20]
[1 2 3 4 5]
[16 17 18 19 20]

[15 40 65 90]
[15 40 65 90]


In [30]:
mat = np.random.randint(1,10,12).reshape(3,4)
print(mat)

[[5 6 2 1]
 [4 8 1 3]
 [1 8 2 9]]


In [31]:
r = mat > 5
print(r)
print(mat[r])
print(~r)
print(mat[~r])

r = (mat > 5) & (mat <=7) # & for and;  | for or
print(r)
print(mat[r])

[[False  True False False]
 [False  True False False]
 [False  True False  True]]
[6 8 8 9]
[[ True False  True  True]
 [ True False  True  True]
 [ True False  True False]]
[5 2 1 4 1 3 1 2]
[[False  True False False]
 [False False False False]
 [False False False False]]
[6]


In [50]:
a = np.array( [ 10,20,30, np.nan])
print(a)
print(np.nan == np.nan)
print(np.isnan(a))
print(np.isnan(a).any())
print(np.isnan(a).all())

print(a%2 == 0)

[10. 20. 30. nan]
False
[False False False  True]
True
False
[ True  True  True False]


C:\Users\admin\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: RuntimeWarning: invalid value encountered in remainder
  


In [33]:
mat = np.random.randint(1,10,12).reshape(3,4)
print(mat)

[[7 9 6 4]
 [4 9 2 1]
 [6 8 1 8]]


In [34]:
r1 = np.where( (mat == 9) | (mat == 8),10,20 )
print(r1)

print(mat)
mat[np.where(mat == 9)] = 100000
print(mat)

[[20 10 20 20]
 [20 10 20 20]
 [20 10 20 10]]
[[7 9 6 4]
 [4 9 2 1]
 [6 8 1 8]]
[[     7 100000      6      4]
 [     4 100000      2      1]
 [     6      8      1      8]]


In [35]:
mat = np.random.randint(1,10,12).reshape(3,4)
print(mat)

[[9 9 4 9]
 [6 6 1 7]
 [6 7 8 7]]


In [36]:
print(mat > 5)
print(mat < 8)
print((mat > 5) & (mat < 8))

[[ True  True False  True]
 [ True  True False  True]
 [ True  True  True  True]]
[[False False  True False]
 [ True  True  True  True]
 [ True  True False  True]]
[[False False False False]
 [ True  True False  True]
 [ True  True False  True]]


In [37]:
mat0 = np.ones(10).reshape(2,5)
print(mat)
mat1 = np.zeros(10).reshape(2,5)

mat2 = np.vstack([mat0 ,mat1])
print(mat2)

mat2 = np.hstack([mat0 ,mat1, mat0])
print(mat2)

[[9 9 4 9]
 [6 6 1 7]
 [6 7 8 7]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1.]]


<h2 style = color:blue>Slicing</h2>

In [38]:
array2 = np.array([2,3,4,5,6,7,9])
print(array2)
arr = array2[4:6].copy()
print(arr)
arr[0]=11
array2
ar1 = np.array([[1,2,3],[4,6,7]])
print(ar1)
ar1.sum(axis = 1)
b = np.array([[2,3,4],[3,5,6]])
ar1.dot(b.transpose())
np.cross(ar1,b)

[2 3 4 5 6 7 9]
[6 7]
[[1 2 3]
 [4 6 7]]


array([[-1,  2, -1],
       [ 1, -3,  2]])

## Sorting

In [39]:
np.sort(ar1,axis = 0,kind = "quicksort")
a = np.arange(2,20)
a.shape
a.reshape(6,3)
np.argsort(a)
np.argmax(a)
np.argmin(a)

0

In [40]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

<h3 style="color:purple">Using normal for loop iteration</h3>

In [41]:
for row in a:
    for cell in row:
        print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


<h3 style="color:purple">For loop with flatten</h3>

In [42]:
for cell in a.flatten():
    print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


<h1 style="color:blue" align="center">nditer</h1>

<h3 style="color:purple">C style ordering</h3>

In [43]:
for x in np.nditer(a, order='C'):
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


<h2 style="color:purple">Fortan style ordering</h2>

In [44]:
for x in np.nditer(a, order='F'):
    print(x)

0
4
8
1
5
9
2
6
10
3
7
11


<h3 style="color:purple">external_loop</h3>

In [45]:
for x in np.nditer(a, flags=['external_loop'],order='F'):
    print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


<h2 style="color:purple">Modify array values while iterating</h2>

In [46]:
for x in np.nditer(a, op_flags=['readwrite']):
    x[...] = x * x

In [47]:
a

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

<h2 style="color:purple">Iterate two broadcastable arrays concurrently</h2>

In [48]:
b = np.arange(3, 15, 4).reshape(3,1)
b

array([[ 3],
       [ 7],
       [11]])

In [49]:
for x, y in np.nditer([a,b]):
    print (x,y)

0 3
1 3
4 3
9 3
16 7
25 7
36 7
49 7
64 11
81 11
100 11
121 11
